services:
  - type: web
    name: bodaSOS
    env: docker
    dockerfilePath: ./Dockerfile
    releaseCommand: bash release.sh
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "false"
      - key: POSTGIS_ENABLED
        value: "false"
      - key: AFRICASTALKING_USERNAME
        value: Pesaree
      - key: AFRICASTALKING_API_KEY
        sync: false
      - key: AFRICASTALKING_SENDER_ID
        value: AFRICASTKNG
      - key: REDIS_URL
        sync: false