# Generated by Django 5.2.14 on 2026-05-31 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sacco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=64, unique=True)),
                ('county', models.CharField(max_length=255)),
                ('sub_county', models.CharField(max_length=255)),
                ('service_radius_km', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaccoComplianceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('CERT_EXPIRED', 'Cert Expired'), ('DISPATCH_MISS', 'Dispatch Miss'), ('SUSPENSION', 'Suspension'), ('REINSTATEMENT', 'Reinstatement')], max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_logs', to='riders.rider')),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_logs', to='saccos.sacco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaccoPayoutBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_jobs', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed')], default='PENDING', max_length=16)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_batches', to=settings.AUTH_USER_MODEL)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_batches', to='saccos.sacco')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
