# Generated by Django 5.2.14 on 2026-05-31 14:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sacco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('chairman_name', models.CharField(max_length=120)),
                ('chairman_phone', models.CharField(blank=True, max_length=32)),
                ('access_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='request_source',
            field=models.CharField(choices=[('web', 'Web'), ('sms', 'SMS'), ('ussd', 'USSD'), ('dispatcher', 'Dispatcher')], default='web', max_length=16),
        ),
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=32, unique=True)),
                ('national_id', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='National ID number must be exactly 8 digits.', regex='^\\d{8}$')])),
                ('ntsa_license_number', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='NTSA license number must be a valid alphanumeric code.', regex='^[A-Z0-9/-]{5,20}$')])),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=16)),
                ('sacco_approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_trained_first_aid', models.BooleanField(default=False)),
                ('profile_photo', models.FileField(blank=True, upload_to='rider-documents/photos/')),
                ('certificate_of_good_conduct', models.FileField(blank=True, upload_to='rider-documents/good-conduct/')),
                ('sacco_membership_card', models.FileField(blank=True, upload_to='rider-documents/sacco-cards/')),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_profile', to=settings.AUTH_USER_MODEL)),
                ('sacco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riders', to='dispatch.sacco')),
            ],
            options={
                'ordering': ['-last_seen_at', 'full_name'],
            },
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='assigned_rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='dispatch.riderprofile'),
        ),
        migrations.DeleteModel(
            name='Rider',
        ),
    ]
