# Generated by Django 5.2.14 on 2026-05-31 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_sacco_emergencyrequest_request_source_riderprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sacco',
            name='chairman_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chairman_sacco', to=settings.AUTH_USER_MODEL),
        ),
    ]
