# Generated by Django 5.2.14 on 2026-05-31 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_sacco_chairman_user'),
        ('patients', '__first__'),
        ('riders', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_rider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DispatchAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('missed', 'Missed'), ('declined', 'Declined')], default='sent', max_length=16)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('timeout_seconds', models.IntegerField(default=45)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_attempts', to='patients.job')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_attempts', to='riders.rider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
