# Generated by Django 5.2.14 on 2026-05-31 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=32)),
                ('license_number', models.CharField(max_length=64)),
                ('license_class', models.CharField(choices=[('F', 'F'), ('G', 'G')], max_length=4)),
                ('phone', models.CharField(max_length=32)),
                ('ntsa_verified', models.BooleanField(default=False)),
                ('coc_verified', models.BooleanField(default=False)),
                ('first_aid_certified', models.BooleanField(default=False)),
                ('first_aid_expiry', models.DateField(blank=True, null=True)),
                ('current_location', models.TextField(blank=True, null=True)),
                ('duty_status', models.CharField(choices=[('OFFLINE', 'Offline'), ('ACTIVE', 'Active'), ('IN_TRANSIT', 'In Transit')], default='OFFLINE', max_length=16)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
                ('dispatch_miss_count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiderLocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DispatchMiss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('missed_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_misses', to='patients.job')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
