# Generated by Django 5.2.14 on 2026-05-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emergency_type', models.CharField(choices=[('ACCIDENT', 'Accident'), ('OBSTETRIC', 'Obstetric'), ('CARDIAC', 'Cardiac')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISPATCHED', 'Dispatched'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='PENDING', max_length=32)),
                ('patient_location', models.TextField()),
                ('patient_address', models.TextField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('sha_job_code', models.CharField(blank=True, max_length=64, unique=True)),
                ('sms_fallback_used', models.BooleanField(default=False)),
                ('session_token', models.CharField(blank=True, default='', max_length=255)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
